# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore-cli" do
  version "0.1.31"

  on_macos do
    on_intel do
      sha256 "5ca80f04cd4a4f89aa7e7e863f39f2b5353f23478de6331896b53bcaf49666f4"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a063637650d52969705b31fc0f8719f20c03e96d0d155fd7526593937d8c440e"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7d81572a8b449d647afccb4e4d20eb2ab2078d9eb818003df2fc84ecb368570"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "037d75371644316cc4b49fcf89fb25134453b881921fef3abfdff1b54f1118ee"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore-cli"
  desc "Scaffold locally, ship edits to a live dev URL, and deploy - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
