# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore" do
  version "0.1.20"

  on_macos do
    on_intel do
      sha256 "7d90542848c59e5183e49af2364e3b3ea40505f3659960b5340d01dd976ecbe3"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b156ecbbbb87438e18d91fb08ce9afbd096717e1fa438f75f49e3b6ad25f1877"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05860a809151e0f854c0fe6089072b5c8af4c10ea8d360b0c9702562f3da2cf2"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4afee694e3cdbd11db81dca848453f4af9ebf65faecde99810c749cfa1655793"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore"
  desc "Build a Benmore app locally and deploy it to benmore.ai - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
