# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore-cli" do
  version "0.1.34"

  on_macos do
    on_intel do
      sha256 "b5764f9e6a5d4015de878de3a4fe7cc21b3069064efb0fb9fef32ff5f5212aad"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43ce5aa69927ab8c39351bb00899153796674675766afbf2ca1921fed3309e7d"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bcb9fd5e527b1ad3c608fe062a6f903f5bdeffc224ad86b7dd9f3df274fd00d9"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0884f3cc217fcdf420467360e6a54ef7771ad371f82a20e90049706aa431a76c"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore-cli"
  desc "Scaffold locally, ship edits to a live dev URL, and deploy - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
