# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore" do
  version "0.1.14"

  on_macos do
    on_intel do
      sha256 "40ae5193838d5c08aaf806f01bd5b4ae33d0a5b5f96f5980864b222c6fc46592"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7aa9993de9c37344541a167b14da0ab83bca503b62a551411fef7c520f970de5"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad21d5525610ac54febf856ed05a3c4779e8cfa5aa6c020346c9983f13131aca"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48b590a145afd930c1fd791380d6d6b1dc7ad1372affe8d8797167bad1f7ba67"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore"
  desc "Build a Benmore app locally and deploy it to benmore.ai - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
