# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore-cli" do
  version "0.1.29"

  on_macos do
    on_intel do
      sha256 "f61590e5540c8170604908b7d77d1607f9431ec1c6824b36b048c94e96a67dba"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "50501627238c4bbcdbfbe8a7aaa16cf95fc0c0a272db4d8e4ef46ba765789633"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c7d54273a189313281ac2330563e27d9a101a47a2e9bfa0d78d1be0283738f5"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6903f85d06823dc8635b1165b653de6c53b067fb16fc797fe854cea04092179c"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore-cli"
  desc "Scaffold locally, ship edits to a live dev URL, and deploy - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
