# This file was generated by GoReleaser. DO NOT EDIT.
cask "benmore" do
  version "0.1.32"

  on_macos do
    on_intel do
      sha256 "de56abfb7f784b61a3b193d41516de433ad7336bc702d0b90b44533a78dfef34"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff9c9f6d80a80a05b7268e69bd9f5e24cf2d08695a43474c747dd11028bc3aaa"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbb8393b5022e56adfafa0e34b221055aec995fa89f900dd6faaa2d41d1a6a52"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1165cdfa6b9530993e161638aa0458457bd753e5714c7e46093a9ab90c7a7ecc"
      url "https://github.com/Benmore-Studio/benmore-cli/releases/download/v#{version}/benmore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "benmore"
  desc "Scaffold locally, ship edits to a live dev URL, and deploy - one Go binary"
  homepage "https://benmore.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "benmore"

  # No zap stanza required

end
